//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.30 at 07:44:23 ÏÂÎç GMT+08:00 
//


package bingo.odata.edm.model.jaxb;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;
import org.w3c.dom.Element;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Documentation" type="{http://schemas.microsoft.com/ado/2008/09/edm}TDocumentation" minOccurs="0"/>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="FunctionImport">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="Documentation" type="{http://schemas.microsoft.com/ado/2008/09/edm}TDocumentation" minOccurs="0"/>
 *                     &lt;element name="Parameter" type="{http://schemas.microsoft.com/ado/2008/09/edm}TFunctionImportParameter" maxOccurs="unbounded" minOccurs="0"/>
 *                     &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;/sequence>
 *                   &lt;attGroup ref="{http://schemas.microsoft.com/ado/2008/09/edm}TFunctionImportAttributes"/>
 *                   &lt;anyAttribute processContents='lax' namespace='##other'/>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="EntitySet">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;group ref="{http://schemas.microsoft.com/ado/2008/09/edm}GEmptyElementExtensibility" minOccurs="0"/>
 *                   &lt;/sequence>
 *                   &lt;attGroup ref="{http://schemas.microsoft.com/ado/2008/09/edm}TEntitySetAttributes"/>
 *                   &lt;anyAttribute processContents='lax' namespace='##other'/>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="AssociationSet">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="Documentation" type="{http://schemas.microsoft.com/ado/2008/09/edm}TDocumentation" minOccurs="0"/>
 *                     &lt;element name="End" maxOccurs="2" minOccurs="0">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;group ref="{http://schemas.microsoft.com/ado/2008/09/edm}GEmptyElementExtensibility" minOccurs="0"/>
 *                             &lt;/sequence>
 *                             &lt;attribute name="Role" type="{http://schemas.microsoft.com/ado/2008/09/edm}TSimpleIdentifier" />
 *                             &lt;attribute name="EntitySet" use="required" type="{http://schemas.microsoft.com/ado/2008/09/edm}TSimpleIdentifier" />
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;/sequence>
 *                   &lt;attribute name="Name" use="required" type="{http://schemas.microsoft.com/ado/2008/09/edm}TSimpleIdentifier" />
 *                   &lt;attribute name="Association" use="required" type="{http://schemas.microsoft.com/ado/2008/09/edm}TQualifiedName" />
 *                   &lt;anyAttribute processContents='lax' namespace='##other'/>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/choice>
 *         &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Name" use="required" type="{http://schemas.microsoft.com/ado/2008/09/edm}TSimpleIdentifier" />
 *       &lt;attribute name="Extends" type="{http://schemas.microsoft.com/ado/2008/09/edm}TSimpleIdentifier" />
 *       &lt;attribute ref="{http://schemas.microsoft.com/ado/2006/04/codegeneration}TypeAccess"/>
 *       &lt;attribute ref="{http://schemas.microsoft.com/ado/2009/02/edm/annotation}LazyLoadingEnabled"/>
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "documentation",
    "functionImportOrEntitySetOrAssociationSet",
    "any"
})
@XmlRootElement(name = "EntityContainer")
public class EntityContainer {

    @XmlElement(name = "Documentation")
    protected TDocumentation documentation;
    @XmlElements({
        @XmlElement(name = "EntitySet", type = EntityContainer.EntitySet.class),
        @XmlElement(name = "FunctionImport", type = EntityContainer.FunctionImport.class),
        @XmlElement(name = "AssociationSet", type = EntityContainer.AssociationSet.class)
    })
    protected List<Object> functionImportOrEntitySetOrAssociationSet;
    @XmlAnyElement(lax = true)
    protected List<Object> any;
    @XmlAttribute(name = "Name", required = true)
    protected String name;
    @XmlAttribute(name = "Extends")
    protected String _extends;
    @XmlAttribute(name = "TypeAccess", namespace = "http://schemas.microsoft.com/ado/2006/04/codegeneration")
    protected TPublicOrInternalAccess typeAccess;
    @XmlAttribute(name = "LazyLoadingEnabled", namespace = "http://schemas.microsoft.com/ado/2009/02/edm/annotation")
    protected Boolean lazyLoadingEnabled;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the documentation property.
     * 
     * @return
     *     possible object is
     *     {@link TDocumentation }
     *     
     */
    public TDocumentation getDocumentation() {
        return documentation;
    }

    /**
     * Sets the value of the documentation property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDocumentation }
     *     
     */
    public void setDocumentation(TDocumentation value) {
        this.documentation = value;
    }

    /**
     * Gets the value of the functionImportOrEntitySetOrAssociationSet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the functionImportOrEntitySetOrAssociationSet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFunctionImportOrEntitySetOrAssociationSet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EntityContainer.EntitySet }
     * {@link EntityContainer.FunctionImport }
     * {@link EntityContainer.AssociationSet }
     * 
     * 
     */
    public List<Object> getFunctionImportOrEntitySetOrAssociationSet() {
        if (functionImportOrEntitySetOrAssociationSet == null) {
            functionImportOrEntitySetOrAssociationSet = new ArrayList<Object>();
        }
        return this.functionImportOrEntitySetOrAssociationSet;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Element }
     * {@link Object }
     * 
     * 
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the extends property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtends() {
        return _extends;
    }

    /**
     * Sets the value of the extends property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtends(String value) {
        this._extends = value;
    }

    /**
     * Gets the value of the typeAccess property.
     * 
     * @return
     *     possible object is
     *     {@link TPublicOrInternalAccess }
     *     
     */
    public TPublicOrInternalAccess getTypeAccess() {
        return typeAccess;
    }

    /**
     * Sets the value of the typeAccess property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPublicOrInternalAccess }
     *     
     */
    public void setTypeAccess(TPublicOrInternalAccess value) {
        this.typeAccess = value;
    }

    /**
     * Gets the value of the lazyLoadingEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLazyLoadingEnabled() {
        return lazyLoadingEnabled;
    }

    /**
     * Sets the value of the lazyLoadingEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLazyLoadingEnabled(Boolean value) {
        this.lazyLoadingEnabled = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Documentation" type="{http://schemas.microsoft.com/ado/2008/09/edm}TDocumentation" minOccurs="0"/>
     *         &lt;element name="End" maxOccurs="2" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;group ref="{http://schemas.microsoft.com/ado/2008/09/edm}GEmptyElementExtensibility" minOccurs="0"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="Role" type="{http://schemas.microsoft.com/ado/2008/09/edm}TSimpleIdentifier" />
     *                 &lt;attribute name="EntitySet" use="required" type="{http://schemas.microsoft.com/ado/2008/09/edm}TSimpleIdentifier" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="Name" use="required" type="{http://schemas.microsoft.com/ado/2008/09/edm}TSimpleIdentifier" />
     *       &lt;attribute name="Association" use="required" type="{http://schemas.microsoft.com/ado/2008/09/edm}TQualifiedName" />
     *       &lt;anyAttribute processContents='lax' namespace='##other'/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "documentation",
        "end",
        "any"
    })
    public static class AssociationSet {

        @XmlElement(name = "Documentation")
        protected TDocumentation documentation;
        @XmlElement(name = "End")
        protected List<EntityContainer.AssociationSet.End> end;
        @XmlAnyElement(lax = true)
        protected List<Object> any;
        @XmlAttribute(name = "Name", required = true)
        protected String name;
        @XmlAttribute(name = "Association", required = true)
        protected String association;
        @XmlAnyAttribute
        private Map<QName, String> otherAttributes = new HashMap<QName, String>();

        /**
         * Gets the value of the documentation property.
         * 
         * @return
         *     possible object is
         *     {@link TDocumentation }
         *     
         */
        public TDocumentation getDocumentation() {
            return documentation;
        }

        /**
         * Sets the value of the documentation property.
         * 
         * @param value
         *     allowed object is
         *     {@link TDocumentation }
         *     
         */
        public void setDocumentation(TDocumentation value) {
            this.documentation = value;
        }

        /**
         * Gets the value of the end property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the end property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEnd().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link EntityContainer.AssociationSet.End }
         * 
         * 
         */
        public List<EntityContainer.AssociationSet.End> getEnd() {
            if (end == null) {
                end = new ArrayList<EntityContainer.AssociationSet.End>();
            }
            return this.end;
        }

        /**
         * Gets the value of the any property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the any property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAny().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Element }
         * {@link Object }
         * 
         * 
         */
        public List<Object> getAny() {
            if (any == null) {
                any = new ArrayList<Object>();
            }
            return this.any;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the association property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAssociation() {
            return association;
        }

        /**
         * Sets the value of the association property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAssociation(String value) {
            this.association = value;
        }

        /**
         * Gets a map that contains attributes that aren't bound to any typed property on this class.
         * 
         * <p>
         * the map is keyed by the name of the attribute and 
         * the value is the string value of the attribute.
         * 
         * the map returned by this method is live, and you can add new attribute
         * by updating the map directly. Because of this design, there's no setter.
         * 
         * 
         * @return
         *     always non-null
         */
        public Map<QName, String> getOtherAttributes() {
            return otherAttributes;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;group ref="{http://schemas.microsoft.com/ado/2008/09/edm}GEmptyElementExtensibility" minOccurs="0"/>
         *       &lt;/sequence>
         *       &lt;attribute name="Role" type="{http://schemas.microsoft.com/ado/2008/09/edm}TSimpleIdentifier" />
         *       &lt;attribute name="EntitySet" use="required" type="{http://schemas.microsoft.com/ado/2008/09/edm}TSimpleIdentifier" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "documentation",
            "any"
        })
        public static class End {

            @XmlElement(name = "Documentation")
            protected TDocumentation documentation;
            @XmlAnyElement(lax = true)
            protected List<Object> any;
            @XmlAttribute(name = "Role")
            protected String role;
            @XmlAttribute(name = "EntitySet", required = true)
            protected String entitySet;

            /**
             * Gets the value of the documentation property.
             * 
             * @return
             *     possible object is
             *     {@link TDocumentation }
             *     
             */
            public TDocumentation getDocumentation() {
                return documentation;
            }

            /**
             * Sets the value of the documentation property.
             * 
             * @param value
             *     allowed object is
             *     {@link TDocumentation }
             *     
             */
            public void setDocumentation(TDocumentation value) {
                this.documentation = value;
            }

            /**
             * Gets the value of the any property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the any property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getAny().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Element }
             * {@link Object }
             * 
             * 
             */
            public List<Object> getAny() {
                if (any == null) {
                    any = new ArrayList<Object>();
                }
                return this.any;
            }

            /**
             * Gets the value of the role property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRole() {
                return role;
            }

            /**
             * Sets the value of the role property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRole(String value) {
                this.role = value;
            }

            /**
             * Gets the value of the entitySet property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEntitySet() {
                return entitySet;
            }

            /**
             * Sets the value of the entitySet property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEntitySet(String value) {
                this.entitySet = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;group ref="{http://schemas.microsoft.com/ado/2008/09/edm}GEmptyElementExtensibility" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attGroup ref="{http://schemas.microsoft.com/ado/2008/09/edm}TEntitySetAttributes"/>
     *       &lt;anyAttribute processContents='lax' namespace='##other'/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "documentation",
        "any"
    })
    public static class EntitySet {

        @XmlElement(name = "Documentation")
        protected TDocumentation documentation;
        @XmlAnyElement(lax = true)
        protected List<Object> any;
        @XmlAttribute(name = "Name", required = true)
        protected String name;
        @XmlAttribute(name = "EntityType", required = true)
        protected String entityType;
        @XmlAttribute(name = "GetterAccess", namespace = "http://schemas.microsoft.com/ado/2006/04/codegeneration")
        protected TAccess getterAccess;
        @XmlAnyAttribute
        private Map<QName, String> otherAttributes = new HashMap<QName, String>();

        /**
         * Gets the value of the documentation property.
         * 
         * @return
         *     possible object is
         *     {@link TDocumentation }
         *     
         */
        public TDocumentation getDocumentation() {
            return documentation;
        }

        /**
         * Sets the value of the documentation property.
         * 
         * @param value
         *     allowed object is
         *     {@link TDocumentation }
         *     
         */
        public void setDocumentation(TDocumentation value) {
            this.documentation = value;
        }

        /**
         * Gets the value of the any property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the any property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAny().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Element }
         * {@link Object }
         * 
         * 
         */
        public List<Object> getAny() {
            if (any == null) {
                any = new ArrayList<Object>();
            }
            return this.any;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the entityType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEntityType() {
            return entityType;
        }

        /**
         * Sets the value of the entityType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEntityType(String value) {
            this.entityType = value;
        }

        /**
         * Gets the value of the getterAccess property.
         * 
         * @return
         *     possible object is
         *     {@link TAccess }
         *     
         */
        public TAccess getGetterAccess() {
            return getterAccess;
        }

        /**
         * Sets the value of the getterAccess property.
         * 
         * @param value
         *     allowed object is
         *     {@link TAccess }
         *     
         */
        public void setGetterAccess(TAccess value) {
            this.getterAccess = value;
        }

        /**
         * Gets a map that contains attributes that aren't bound to any typed property on this class.
         * 
         * <p>
         * the map is keyed by the name of the attribute and 
         * the value is the string value of the attribute.
         * 
         * the map returned by this method is live, and you can add new attribute
         * by updating the map directly. Because of this design, there's no setter.
         * 
         * 
         * @return
         *     always non-null
         */
        public Map<QName, String> getOtherAttributes() {
            return otherAttributes;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Documentation" type="{http://schemas.microsoft.com/ado/2008/09/edm}TDocumentation" minOccurs="0"/>
     *         &lt;element name="Parameter" type="{http://schemas.microsoft.com/ado/2008/09/edm}TFunctionImportParameter" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attGroup ref="{http://schemas.microsoft.com/ado/2008/09/edm}TFunctionImportAttributes"/>
     *       &lt;anyAttribute processContents='lax' namespace='##other'/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "documentation",
        "parameter",
        "any"
    })
    public static class FunctionImport {

        @XmlElement(name = "Documentation")
        protected TDocumentation documentation;
        @XmlElement(name = "Parameter")
        protected List<TFunctionImportParameter> parameter;
        @XmlAnyElement(lax = true)
        protected List<Object> any;
        @XmlAttribute(name = "Name", required = true)
        protected String name;
        @XmlAttribute(name = "ReturnType")
        protected String returnType;
        @XmlAttribute(name = "EntitySet")
        protected String entitySet;
        @XmlAttribute(name = "MethodAccess", namespace = "http://schemas.microsoft.com/ado/2006/04/codegeneration")
        protected TAccess methodAccess;
        @XmlAnyAttribute
        private Map<QName, String> otherAttributes = new HashMap<QName, String>();

        /**
         * Gets the value of the documentation property.
         * 
         * @return
         *     possible object is
         *     {@link TDocumentation }
         *     
         */
        public TDocumentation getDocumentation() {
            return documentation;
        }

        /**
         * Sets the value of the documentation property.
         * 
         * @param value
         *     allowed object is
         *     {@link TDocumentation }
         *     
         */
        public void setDocumentation(TDocumentation value) {
            this.documentation = value;
        }

        /**
         * Gets the value of the parameter property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the parameter property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getParameter().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TFunctionImportParameter }
         * 
         * 
         */
        public List<TFunctionImportParameter> getParameter() {
            if (parameter == null) {
                parameter = new ArrayList<TFunctionImportParameter>();
            }
            return this.parameter;
        }

        /**
         * Gets the value of the any property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the any property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAny().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Element }
         * {@link Object }
         * 
         * 
         */
        public List<Object> getAny() {
            if (any == null) {
                any = new ArrayList<Object>();
            }
            return this.any;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the returnType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReturnType() {
            return returnType;
        }

        /**
         * Sets the value of the returnType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReturnType(String value) {
            this.returnType = value;
        }

        /**
         * Gets the value of the entitySet property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEntitySet() {
            return entitySet;
        }

        /**
         * Sets the value of the entitySet property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEntitySet(String value) {
            this.entitySet = value;
        }

        /**
         * Gets the value of the methodAccess property.
         * 
         * @return
         *     possible object is
         *     {@link TAccess }
         *     
         */
        public TAccess getMethodAccess() {
            return methodAccess;
        }

        /**
         * Sets the value of the methodAccess property.
         * 
         * @param value
         *     allowed object is
         *     {@link TAccess }
         *     
         */
        public void setMethodAccess(TAccess value) {
            this.methodAccess = value;
        }

        /**
         * Gets a map that contains attributes that aren't bound to any typed property on this class.
         * 
         * <p>
         * the map is keyed by the name of the attribute and 
         * the value is the string value of the attribute.
         * 
         * the map returned by this method is live, and you can add new attribute
         * by updating the map directly. Because of this design, there's no setter.
         * 
         * 
         * @return
         *     always non-null
         */
        public Map<QName, String> getOtherAttributes() {
            return otherAttributes;
        }

    }

}
