//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.30 at 07:44:23 ÏÂÎç GMT+08:00 
//


package bingo.odata.edm.model.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the bingo.odata.edm.model.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Schema_QNAME = new QName("http://schemas.microsoft.com/ado/2008/09/edm", "Schema");
    private final static QName _TFunctionDefiningExpression_QNAME = new QName("http://schemas.microsoft.com/ado/2008/09/edm", "DefiningExpression");
    private final static QName _TFunctionReturnType_QNAME = new QName("http://schemas.microsoft.com/ado/2008/09/edm", "ReturnType");
    private final static QName _TFunctionParameter_QNAME = new QName("http://schemas.microsoft.com/ado/2008/09/edm", "Parameter");
    private final static QName _TRowTypeProperty_QNAME = new QName("http://schemas.microsoft.com/ado/2008/09/edm", "Property");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: bingo.odata.edm.model.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TEntityKeyElement }
     * 
     */
    public TEntityKeyElement createTEntityKeyElement() {
        return new TEntityKeyElement();
    }

    /**
     * Create an instance of {@link TComplexType }
     * 
     */
    public TComplexType createTComplexType() {
        return new TComplexType();
    }

    /**
     * Create an instance of {@link TDocumentation }
     * 
     */
    public TDocumentation createTDocumentation() {
        return new TDocumentation();
    }

    /**
     * Create an instance of {@link TReferentialConstraintRoleElement }
     * 
     */
    public TReferentialConstraintRoleElement createTReferentialConstraintRoleElement() {
        return new TReferentialConstraintRoleElement();
    }

    /**
     * Create an instance of {@link TReferenceType }
     * 
     */
    public TReferenceType createTReferenceType() {
        return new TReferenceType();
    }

    /**
     * Create an instance of {@link EntityContainer.FunctionImport }
     * 
     */
    public EntityContainer.FunctionImport createEntityContainerFunctionImport() {
        return new EntityContainer.FunctionImport();
    }

    /**
     * Create an instance of {@link TText }
     * 
     */
    public TText createTText() {
        return new TText();
    }

    /**
     * Create an instance of {@link TProperty }
     * 
     */
    public TProperty createTProperty() {
        return new TProperty();
    }

    /**
     * Create an instance of {@link TXmlOrText }
     * 
     */
    public TXmlOrText createTXmlOrText() {
        return new TXmlOrText();
    }

    /**
     * Create an instance of {@link TFunctionImportParameter }
     * 
     */
    public TFunctionImportParameter createTFunctionImportParameter() {
        return new TFunctionImportParameter();
    }

    /**
     * Create an instance of {@link TConstraint }
     * 
     */
    public TConstraint createTConstraint() {
        return new TConstraint();
    }

    /**
     * Create an instance of {@link TPropertyRef }
     * 
     */
    public TPropertyRef createTPropertyRef() {
        return new TPropertyRef();
    }

    /**
     * Create an instance of {@link TCollectionType }
     * 
     */
    public TCollectionType createTCollectionType() {
        return new TCollectionType();
    }

    /**
     * Create an instance of {@link TComplexTypeProperty }
     * 
     */
    public TComplexTypeProperty createTComplexTypeProperty() {
        return new TComplexTypeProperty();
    }

    /**
     * Create an instance of {@link EntityContainer.AssociationSet }
     * 
     */
    public EntityContainer.AssociationSet createEntityContainerAssociationSet() {
        return new EntityContainer.AssociationSet();
    }

    /**
     * Create an instance of {@link TRowType }
     * 
     */
    public TRowType createTRowType() {
        return new TRowType();
    }

    /**
     * Create an instance of {@link TEntityType }
     * 
     */
    public TEntityType createTEntityType() {
        return new TEntityType();
    }

    /**
     * Create an instance of {@link TNavigationProperty }
     * 
     */
    public TNavigationProperty createTNavigationProperty() {
        return new TNavigationProperty();
    }

    /**
     * Create an instance of {@link TSchema }
     * 
     */
    public TSchema createTSchema() {
        return new TSchema();
    }

    /**
     * Create an instance of {@link TAssociationEnd }
     * 
     */
    public TAssociationEnd createTAssociationEnd() {
        return new TAssociationEnd();
    }

    /**
     * Create an instance of {@link TOnAction }
     * 
     */
    public TOnAction createTOnAction() {
        return new TOnAction();
    }

    /**
     * Create an instance of {@link TUsing }
     * 
     */
    public TUsing createTUsing() {
        return new TUsing();
    }

    /**
     * Create an instance of {@link EntityContainer }
     * 
     */
    public EntityContainer createEntityContainer() {
        return new EntityContainer();
    }

    /**
     * Create an instance of {@link TEntityProperty }
     * 
     */
    public TEntityProperty createTEntityProperty() {
        return new TEntityProperty();
    }

    /**
     * Create an instance of {@link EntityContainer.EntitySet }
     * 
     */
    public EntityContainer.EntitySet createEntityContainerEntitySet() {
        return new EntityContainer.EntitySet();
    }

    /**
     * Create an instance of {@link TFunction }
     * 
     */
    public TFunction createTFunction() {
        return new TFunction();
    }

    /**
     * Create an instance of {@link EntityContainer.AssociationSet.End }
     * 
     */
    public EntityContainer.AssociationSet.End createEntityContainerAssociationSetEnd() {
        return new EntityContainer.AssociationSet.End();
    }

    /**
     * Create an instance of {@link TFunctionParameter }
     * 
     */
    public TFunctionParameter createTFunctionParameter() {
        return new TFunctionParameter();
    }

    /**
     * Create an instance of {@link TTypeRef }
     * 
     */
    public TTypeRef createTTypeRef() {
        return new TTypeRef();
    }

    /**
     * Create an instance of {@link TAssociation }
     * 
     */
    public TAssociation createTAssociation() {
        return new TAssociation();
    }

    /**
     * Create an instance of {@link TFunctionReturnType }
     * 
     */
    public TFunctionReturnType createTFunctionReturnType() {
        return new TFunctionReturnType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TSchema }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/ado/2008/09/edm", name = "Schema")
    public JAXBElement<TSchema> createSchema(TSchema value) {
        return new JAXBElement<TSchema>(_Schema_QNAME, TSchema.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/ado/2008/09/edm", name = "DefiningExpression", scope = TFunction.class)
    public JAXBElement<String> createTFunctionDefiningExpression(String value) {
        return new JAXBElement<String>(_TFunctionDefiningExpression_QNAME, String.class, TFunction.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TFunctionReturnType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/ado/2008/09/edm", name = "ReturnType", scope = TFunction.class)
    public JAXBElement<TFunctionReturnType> createTFunctionReturnType(TFunctionReturnType value) {
        return new JAXBElement<TFunctionReturnType>(_TFunctionReturnType_QNAME, TFunctionReturnType.class, TFunction.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TFunctionParameter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/ado/2008/09/edm", name = "Parameter", scope = TFunction.class)
    public JAXBElement<TFunctionParameter> createTFunctionParameter(TFunctionParameter value) {
        return new JAXBElement<TFunctionParameter>(_TFunctionParameter_QNAME, TFunctionParameter.class, TFunction.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TProperty }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/ado/2008/09/edm", name = "Property", scope = TRowType.class)
    public JAXBElement<TProperty> createTRowTypeProperty(TProperty value) {
        return new JAXBElement<TProperty>(_TRowTypeProperty_QNAME, TProperty.class, TRowType.class, value);
    }

}
