//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.30 at 07:44:23 обнГ GMT+08:00 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://schemas.microsoft.com/ado/2008/09/edm", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package bingo.odata.edm.model.jaxb;
