//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.30 at 07:44:23 ÏÂÎç GMT+08:00 
//


package bingo.odata.edm.model.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TPublicOrInternalAccess.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TPublicOrInternalAccess">
 *   &lt;restriction base="{http://schemas.microsoft.com/ado/2006/04/codegeneration}TAccess">
 *     &lt;enumeration value="Public"/>
 *     &lt;enumeration value="Internal"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TPublicOrInternalAccess", namespace = "http://schemas.microsoft.com/ado/2006/04/codegeneration")
@XmlEnum(TAccess.class)
public enum TPublicOrInternalAccess {

    @XmlEnumValue("Public")
    PUBLIC(TAccess.PUBLIC),
    @XmlEnumValue("Internal")
    INTERNAL(TAccess.INTERNAL);
    private final TAccess value;

    TPublicOrInternalAccess(TAccess v) {
        value = v;
    }

    public TAccess value() {
        return value;
    }

    public static TPublicOrInternalAccess fromValue(TAccess v) {
        for (TPublicOrInternalAccess c: TPublicOrInternalAccess.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v.toString());
    }

}
