//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.30 at 07:44:23 ÏÂÎç GMT+08:00 
//


package bingo.odata.edm.model.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TStoreGeneratedPattern.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TStoreGeneratedPattern">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="None"/>
 *     &lt;enumeration value="Identity"/>
 *     &lt;enumeration value="Computed"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TStoreGeneratedPattern", namespace = "http://schemas.microsoft.com/ado/2009/02/edm/annotation")
@XmlEnum
public enum TStoreGeneratedPattern {

    @XmlEnumValue("None")
    NONE("None"),
    @XmlEnumValue("Identity")
    IDENTITY("Identity"),
    @XmlEnumValue("Computed")
    COMPUTED("Computed");
    private final String value;

    TStoreGeneratedPattern(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TStoreGeneratedPattern fromValue(String v) {
        for (TStoreGeneratedPattern c: TStoreGeneratedPattern.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
